application: html5mduel
version: 3
runtime: python
api_version: 1

handlers:
- url: /
  static_files: mduel.html
  upload: mduel.html

- url: /manifest.cache
  static_files: manifest.cache
  upload: manifest.cache

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /png
  script: png.py

- url: /player
  script: images/player.png

- url: /playersample
  script: images/playersample.png

- url: /playersample
  script: images/spites.png
  
- url: /js
  static_dir: js
  
- url: /generate
  script: generate.py
