application: html5mduel
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: mduel.html
  upload: mduel.html

- url: /manifest.cache
  static_files: manifest.cache
  upload: manifest.cache

- url: /images/player.png
  static_files: images/player.png
  upload: images/player.png

- url: /player.png
  script: player.png
 
- url: /images/sprites.png
  static_files: images/sprites.png
  upload: images/sprites.png

- url: /js
  static_dir: js
  
- url: /test
  script: test.py
